CURRENT_TURN: 15
JUMLAH_ITEM_DI_SHOP: 5
SHOP_ITEMS:
- {NAME: DAGING_KUDA, QUANTITY: 10}
- {NAME: SUSU, QUANTITY: 2}
- {NAME: DAGING_BERUANG, QUANTITY: 1}
- {NAME: DAGING_DOMBA, QUANTITY: 3}
- {NAME: SIRIP_HIU, QUANTITY: 5}
