JUMLAH_GULDEN: 30
JUMLAH_DECK: 36
JUMLAH_DECK_AKTIF: 0
DECK_AKTIF: []
JUMLAH_KARTU_LADANG: 1
KARTU_LADANG:
- LOKASI_KARTU: B02
  KARTU: BIJI_JAGUNG
  UMUR_BERAT: 0
  JUMLAH_ITEM_AKTIF: 1
  ITEMS: [PROTECT]
