JUMLAH_GULDEN: 300
JUMLAH_DECK: 27
JUMLAH_DECK_AKTIF: 6
DECK_AKTIF:
- {LOKASI_KARTU: A01, KARTU: BERUANG}
- {LOKASI_KARTU: B01, KARTU: PROTECT}
- {LOKASI_KARTU: C01, KARTU: SAPI}
- {LOKASI_KARTU: D01, KARTU: HIU_DARAT}
- {LOKASI_KARTU: E01, KARTU: DAGING_DOMBA}
- {LOKASI_KARTU: F01, KARTU: JAGUNG}
JUMLAH_KARTU_LADANG: 1
KARTU_LADANG:
- {LOKASI_KARTU: B02, KARTU: AYAM, UMUR_BERAT: 0, JUMLAH_ITEM_AKTIF: 0}
