JUMLAH_GULDEN: 500
JUMLAH_DECK: 29
JUMLAH_DECK_AKTIF: 6
DECK_AKTIF:
- {LOKASI_KARTU: A01, KARTU: BERUANG}
- {LOKASI_KARTU: B01, KARTU: BIJI_JAGUNG}
- {LOKASI_KARTU: C01, KARTU: ACCELERATE}
- {LOKASI_KARTU: D01, KARTU: DESTROY}
- {LOKASI_KARTU: E01, KARTU: TELUR}
- {LOKASI_KARTU: F01, KARTU: DAGING_KUDA}
JUMLAH_KARTU_LADANG: 2
KARTU_LADANG:
- LOKASI_KARTU: A01
  KARTU: DOMBA
  UMUR_BERAT: 5
  JUMLAH_ITEM_AKTIF: 2
  ITEMS: [ACCELERATE, PROTECT]
- {LOKASI_KARTU: B02, KARTU: AYAM, UMUR_BERAT: 0, JUMLAH_ITEM_AKTIF: 0}
