JUMLAH_GULDEN: 300
JUMLAH_DECK: 34
JUMLAH_DECK_AKTIF: 6
DECK_AKTIF:
- {LOKASI_KARTU: A1, KARTU: BERUANG}
- {LOKASI_KARTU: A2, KARTU: JAGUNG}
- {LOKASI_KARTU: A3, KARTU: DOMBA}
- {LOKASI_KARTU: A4, KARTU: PROTECT}
- {LOKASI_KARTU: A5, KARTU: STROBERI}
- {LOKASI_KARTU: B1, KARTU: BERUANG}
JUMLAH_KARTU_LADANG: 1
KARTU_LADANG:
- {LOKASI_KARTU: B2, KARTU: AYAM, UMUR_BERAT: 0, JUMLAH_ITEM_AKTIF: 0}
