JUMLAH_GULDEN: 500
JUMLAH_DECK: 35
JUMLAH_DECK_AKTIF: 6
DECK_AKTIF:
- {LOKASI_KARTU: A1, KARTU: BERUANG}
- {LOKASI_KARTU: A2, KARTU: DESTROY}
- {LOKASI_KARTU: A3, KARTU: DELAY}
- {LOKASI_KARTU: A4, KARTU: BIJI_STROBERI}
- {LOKASI_KARTU: A5, KARTU: STROBERI}
- {LOKASI_KARTU: B1, KARTU: BERUANG}
JUMLAH_KARTU_LADANG: 2
KARTU_LADANG:
- LOKASI_KARTU: A1
  KARTU: DOMBA
  UMUR_BERAT: 5
  JUMLAH_ITEM_AKTIF: 2
  ITEMS: [ACCELERATE, PROTECT]
- {LOKASI_KARTU: B2, KARTU: AYAM, UMUR_BERAT: 0, JUMLAH_ITEM_AKTIF: 0}
