JUMLAH_GULDEN: 500
JUMLAH_DECK: 39
JUMLAH_DECK_AKTIF: 2
DECK_AKTIF:
  - LOKASI_KARTU: A01
    KARTU: BERUANG
  - LOKASI_KARTU: B01
    KARTU: BERUANG
JUMLAH_KARTU_LADANG: 2
KARTU_LADANG:
  - LOKASI_KARTU: A01
    KARTU: DOMBA
    UMUR_BERAT: 5
    JUMLAH_ITEM_AKTIF: 3
    ITEMS:
      - ACCELERATE
      - DELAY
      - PROTECT
  - LOKASI_KARTU: B02
    KARTU: AYAM
    UMUR_BERAT: 0
    JUMLAH_ITEM_AKTIF: 0
    ITEMS: []
